### ISSUE TITLE
FatalProcessOutOfMemory in Node.js when executing rules

### ISSUE THREAD

**Issue by vilchik-elena** [SonarSource/sonar-css#136] opened 2018-10-25 08:55 UTC
We don't have a reproducer, here are the logs of failure.

```
2018-10-17T03:25:11.1057138Z 03:25:11.105 INFO: Sensor SonarCSS Rules [cssfamily]
2018-10-17T03:25:11.1057138Z 03:25:11.105 DEBUG: Checking node version
2018-10-17T03:25:11.4650888Z 03:25:11.465 DEBUG: Using Node.js v8.12.0
2018-10-17T03:25:11.4650888Z 03:25:11.465 DEBUG: Deploying bundle to E:\tfsbuild\Agent3\_work\13\.sonarqube\out\.sonar\MA_PORTAL_MA_PORTAL_90808C1F-EBF9-402D-BD31-B34DA66E5B1D
2018-10-17T03:27:02.7920878Z ##[error]03:27:02.651 ERROR: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2018-10-17T03:27:02.8077118Z 03:27:02.651 ERROR: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
2018-10-17T03:27:03.6045907Z ##[error]03:27:03.604 ERROR:  1: node_module_register
2018-10-17T03:27:03.6045907Z 03:27:03.604 ERROR:  1: node_module_register
2018-10-17T03:27:03.6202162Z ##[error]03:27:03.604 ERROR:  2: v8::internal::FatalProcessOutOfMemory
03:27:03.604 ERROR:  3: v8::internal::FatalProcessOutOfMemory
03:27:03.604 ERROR:  4: v8::internal::Factory::NewRawTwoByteString
03:27:03.604 ERROR:  5: v8::internal::Smi::SmiPrint
03:27:03.604 ERROR:  6: v8::internal::StackGuard::HandleInterrupt`s
03:27:03.604 ERROR:  7: v8::String::WriteUtf8
03:27:03.604 ERROR:  8: v8::internal::compiler::Type::Negative31
03:27:03.604 ERROR:  9: node::Buffer::New
03:27:03.604 ERROR: 10: node::Buffer::New
03:27:03.604 ERROR: 11: v8::internal::wasm::SignatureMap::Find
03:27:03.604 ERROR: 12: v8::internal::Builtins::CallableFor
2018-10-17T03:27:03.8233419Z 03:27:03.604 ERROR:  2: v8::internal::FatalProcessOutOfMemory
2018-10-17T03:27:03.8233419Z 03:27:03.604 ERROR:  3: v8::internal::FatalProcessOutOfMemory
2018-10-17T03:27:03.8545952Z 03:27:03.604 ERROR:  4: v8::internal::Factory::NewRawTwoByteString
2018-10-17T03:27:04.0420932Z 03:27:03.604 ERROR:  5: v8::internal::Smi::SmiPrint
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR:  6: v8::internal::StackGuard::HandleInterrupts
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR:  7: v8::String::WriteUtf8
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR:  8: v8::internal::compiler::Type::Negative31
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR:  9: node::Buffer::New
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR: 10: node::Buffer::New
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR: 11: v8::internal::wasm::SignatureMap::Find
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR: 12: v8::internal::Builtins::CallableFor
2018-10-17T03:27:04.4014717Z ##[error]03:27:03.604 ERROR: 13: v8::internal::Builtins::CallableFor
03:27:03.604 ERROR: 14: v8::internal::Builtins::CallableFor
03:27:03.604 ERROR: 15: 0000021270F843C1
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR: 13: v8::internal::Builtins::CallableFor
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR: 14: v8::internal::Builtins::CallableFor
2018-10-17T03:27:04.4014717Z 03:27:03.604 ERROR: 15: 0000021270F843C1
2018-10-17T03:27:04.4014717Z ##[error]03:27:03.838 ERROR: Analysis didn't terminate normally, please verify ERROR and WARN logs above. Exit code 3
2018-10-17T03:27:04.4014717Z 03:27:03.838 ERROR: Analysis didn't terminate normally, please verify ERROR and WARN logs above. Exit code 3
2018-10-17T03:27:04.4014717Z 03:27:03.838 INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=112733ms
```

**Comment by timmyz** [comment] 2019-04-01 08:35
```
INFO: Sensor SonarCSS Metrics [cssfamily]
INFO: Sensor SonarCSS Metrics [cssfamily] (done) | time=285ms
INFO: Sensor SonarCSS Rules [cssfamily]
ERROR: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
ERROR:  1: 0x8dc510 node::Abort() [stylelint]
ERROR:  2: 0x8dc55c  [stylelint]
ERROR:  3: 0xad9b5e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [stylelint]
ERROR:  4: 0xad9d94 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [stylelint]
ERROR:  5: 0xec7bf2  [stylelint]
ERROR:  6: 0xec7cf8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [stylelint]
ERROR:  7: 0xed3dd2 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [stylelint]
ERROR:  8: 0xed4704 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [stylelint]
ERROR:  9: 0xed7371 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [stylelint]
ERROR: 10: 0xe9f655  [stylelint]
ERROR: 11: 0xea6eca v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [stylelint]
ERROR: 12: 0xff09ad v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [stylelint]
ERROR: 13: 0x1194c0e v8::internal::Runtime_StringCharCodeAt(int, v8::internal::Object**, v8::internal::Isolate*) [stylelint]
ERROR: 14: 0x4c5cdd5be1d 
ERROR: Analysis didn't terminate normally, please verify ERROR and WARN logs above. Exit code 134
INFO: Sensor SonarCSS Rules [cssfamily] (done) | time=162255ms
```
similar fatal error here

**Comment by vilchik-elena** [comment] 2019-04-01 08:46
@timmyz could you provide a reproducer project?

**Comment by timmyz** [comment] 2019-04-01 08:50
https://github.com/ant-design/ant-design-pro, i do dev based on it.
btw, i'm using jenkins+sonar scanner to run the scan, virtual machine is 2C8G, only jenkins + sonarqube are running on it.

**Comment by nicolas-harraudeau-sonarsource** [comment] 2019-05-06 11:47
@timmyz I ran an analysis on the ant-design-pro without any issue. Could you tell us is you have a `NODE_OPTIONS` environment variable set? If so what is its value?

It should be possible to increase the heap size by setting in your environment `NODE_OPTIONS=--max_old_space_size=...`

Example:
```
NODE_OPTIONS=--max_old_space_size=1096 sonar-scanner
```
If you need a particularly big amount of memory we would be interested in having a minimal reproducer. Knowing the specific file creating this issue would guide us if there is a memory leak.

**Comment by timmyz** [comment] 2019-05-13 07:01
i can't reproduce it either o.0 .....
i've upgraded jenkins and sonar up to the latest version, it seems to be fine for now. so just close this issue i think. 🤔

**Closed** 2019-05-13 07:15 UTC
Labels: bug, hardening

**Comment by timmyz** [comment] 2019-09-09 09:04
hey @vilchik-elena , it seems i've figured out what cause this exception.
the problem key is that this plugin seems not to ignore the exclusions. it digged into the directories like /node_modules/** and dist/** which contains large .css files. 
so if i clean the jenkins workspace each time before start sonar scanner, this problem won't occur.

so i think you should add some logic to read the exclusion config? maybe in following position.
https://github.com/SonarSource/sonar-css/blob/f379e20ac593871801a591909f7971ea99717315/sonar-css-plugin/src/main/java/org/sonar/css/plugin/StylelintCommandProvider.java#L48-L56

**Comment by timmyz** [comment] 2019-09-09 09:07
cc to @nicolas-harraudeau-sonarsource , thx for your help btw.
