### ISSUE TITLE
Rule css:S4668: False positives alerts on inline comments in Less files

### ISSUE THREAD

**Issue by zuza-str** [SonarSource/sonar-css#304] opened 2020-12-18 15:00 UTC
The CSS:S4668 rule checks if the comment style is compliant with the W3C specifications and is defined only by using /* ... */. as the use of // is not supported on all browsers and can lead to unexpected results.

However, Less supports both types of comments (see Comments section at http://lesscss.org/#overview), so in this case, the rule causes raising false-positive alerts. 

Could this rule be enhanced and allow inline comments in .less files?

**Comment by andrea-guarino-sonarsource** [comment] 2021-02-18 14:16
hi @zuza-str , 
I cannot reproduce this issue.
What version of sonar-css are you using? 
I tried with latest and version 1.3.1

**Comment by vilchik-elena** [comment] 2021-07-16 12:59
Can't reproduce, closing the issue

**Closed by vilchik-elena** 2021-07-16 12:59 UTC
